package execution

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"mit.edu/dsg/godb/catalog"
	"mit.edu/dsg/godb/common"
	"mit.edu/dsg/godb/indexing"
	"mit.edu/dsg/godb/planner"
	"mit.edu/dsg/godb/storage"
	"mit.edu/dsg/godb/transaction"
)

// insertRows is a genericx helper to insert raw expressions into a table.
// It handles the creation and draining of an InsertExecutor.
func insertRows(t *testing.T, th *TableHeap, rows [][]planner.Expr, indexes []indexing.Index) {
	valuesNode := planner.NewValuesNode(rows, th.StorageSchema().GetFieldTypes())
	valuesExec := NewValuesExecutor(valuesNode)

	insertNode := planner.NewInsertNode(th.oid, valuesNode)
	insertExec := NewInsertExecutor(insertNode, valuesExec, th, indexes)

	require.NoError(t, insertExec.Init(NewExecutorContext(nil)))

	for insertExec.Next() {
	}

	require.NoError(t, insertExec.Error())
	require.NoError(t, insertExec.Close())
}

// Schema: (sale_id int, revenue int, cost int, region string, category string)
func setupSalesTable(t *testing.T, bp *storage.BufferPool) *TableHeap {
	schema := &catalog.Table{
		Oid:  999,
		Name: "sales",
		Columns: []catalog.Column{
			{Name: "sale_id", Type: common.IntType},
			{Name: "revenue", Type: common.IntType},
			{Name: "cost", Type: common.IntType},
			{Name: "region", Type: common.StringType},
			{Name: "category", Type: common.StringType},
		},
	}

	th, err := NewTableHeap(schema, bp, storage.NoopLogManager{}, nil)
	require.NoError(t, err)

	return th
}

func insertSalesData(t *testing.T, th *TableHeap, indexes []indexing.Index, numRows int) {
	var rows [][]planner.Expr
	for i := 0; i < numRows; i++ {
		region := "US"
		if i%2 != 0 {
			region = "EU"
		}

		category := "Clothing"
		if i%3 == 0 {
			category = "Electronics"
		} else if i%3 == 1 {
			category = "Books"
		}

		row := []planner.Expr{
			planner.NewConstantValueExpression(common.NewIntValue(int64(i))),       // id
			planner.NewConstantValueExpression(common.NewIntValue(int64(i * 200))), // revenue
			planner.NewConstantValueExpression(common.NewIntValue(int64(i * 100))), // cost
			planner.NewConstantValueExpression(common.NewStringValue(region)),      // region
			planner.NewConstantValueExpression(common.NewStringValue(category)),    // category
		}
		rows = append(rows, row)
	}

	insertRows(t, th, rows, indexes)
}

// Shipments Schema: (ship_id, sale_id, carrier)
func setupShipmentTable(t *testing.T, bp *storage.BufferPool) *TableHeap {
	shipCols := []catalog.Column{
		{Name: "ship_id", Type: common.IntType},
		{Name: "sale_id", Type: common.IntType}, // Join Key
		{Name: "carrier", Type: common.StringType},
	}
	schema := &catalog.Table{Oid: 2, Name: "shipments", Columns: shipCols}
	th, err := NewTableHeap(schema, bp, storage.NoopLogManager{}, nil)
	require.NoError(t, err)
	return th
}

// insertShipmentData populates the shipment table.
// ship_id: 100 + 2 * i
// sale_id: i (Matches the IDs generated by insertSalesData)
// carrier: Rotates FedEx/UPS/DHL/USPS
func insertShipmentData(t *testing.T, th *TableHeap, indexes []indexing.Index, numRows int) {
	var rows [][]planner.Expr
	carriers := []string{"FedEx", "UPS", "DHL", "USPS"}

	for i := 0; i < numRows; i++ {
		row := []planner.Expr{
			planner.NewConstantValueExpression(common.NewIntValue(int64(100 + 2*i))), // ship_id
			planner.NewConstantValueExpression(common.NewIntValue(int64(i))),         // sale_id
			planner.NewConstantValueExpression(common.NewStringValue(carriers[i%4])), // carrier
		}
		rows = append(rows, row)
	}
	insertRows(t, th, rows, indexes)
}

// Sales (Left): IDs 1, 2, 3, 4
// Shipments (Right): IDs 1, 3, 6 (Foreign Key to Sales)
func insertJoinData_Basic(t *testing.T, sales *TableHeap, shipment *TableHeap, salesIndexes []indexing.Index, shipmentIndexes []indexing.Index) {
	salesRows := [][]planner.Expr{
		{
			planner.NewConstantValueExpression(common.NewIntValue(1)),             // sale_id (Match)
			planner.NewConstantValueExpression(common.NewIntValue(100)),           // revenue
			planner.NewConstantValueExpression(common.NewIntValue(50)),            // cost
			planner.NewConstantValueExpression(common.NewStringValue("US")),       // region
			planner.NewConstantValueExpression(common.NewStringValue("Clothing")), // category
		},
		{
			planner.NewConstantValueExpression(common.NewIntValue(2)), // sale_id (No Match in Shipment)
			planner.NewConstantValueExpression(common.NewIntValue(200)),
			planner.NewConstantValueExpression(common.NewIntValue(100)),
			planner.NewConstantValueExpression(common.NewStringValue("EU")),
			planner.NewConstantValueExpression(common.NewStringValue("Electronics")),
		},
		{
			planner.NewConstantValueExpression(common.NewIntValue(3)), // sale_id (Match)
			planner.NewConstantValueExpression(common.NewIntValue(300)),
			planner.NewConstantValueExpression(common.NewIntValue(150)),
			planner.NewConstantValueExpression(common.NewStringValue("US")),
			planner.NewConstantValueExpression(common.NewStringValue("Books")),
		},
		{
			planner.NewConstantValueExpression(common.NewIntValue(4)), // sale_id (No Match in Shipment)
			planner.NewConstantValueExpression(common.NewIntValue(400)),
			planner.NewConstantValueExpression(common.NewIntValue(200)),
			planner.NewConstantValueExpression(common.NewStringValue("EU")),
			planner.NewConstantValueExpression(common.NewStringValue("Clothing")),
		},
	}
	insertRows(t, sales, salesRows, salesIndexes)

	shipmentRows := [][]planner.Expr{
		{
			planner.NewConstantValueExpression(common.NewIntValue(101)), // ship_id
			planner.NewConstantValueExpression(common.NewIntValue(1)),   // sale_id (Match)
			planner.NewConstantValueExpression(common.NewStringValue("FedEx")),
		},
		{
			planner.NewConstantValueExpression(common.NewIntValue(102)), // ship_id
			planner.NewConstantValueExpression(common.NewIntValue(3)),   // sale_id (Match)
			planner.NewConstantValueExpression(common.NewStringValue("UPS")),
		},
		{
			planner.NewConstantValueExpression(common.NewIntValue(103)), // ship_id
			planner.NewConstantValueExpression(common.NewIntValue(6)),   // sale_id (No Match in Sales)
			planner.NewConstantValueExpression(common.NewStringValue("DHL")),
		},
	}
	insertRows(t, shipment, shipmentRows, shipmentIndexes)
}

// verifyIndexMatch checks if the index contains an entry for the specific key values pointing to targetRid.
func verifyIndexMatch(t *testing.T, idx indexing.Index, keyValues []common.Value, targetRid common.RecordID, present bool) {
	keySchema := idx.Metadata().KeySchema
	keyTuple := storage.FromValues(keyValues...)
	keyRaw := make([]byte, keySchema.BytesPerTuple())
	keyTuple.WriteToBuffer(keyRaw, keySchema)

	rids, err := idx.ScanKey(idx.Metadata().AsKey(keyRaw), nil, nil)
	require.NoError(t, err)

	found := false
	for _, r := range rids {
		if r == targetRid {
			found = true
			break
		}
	}

	assert.Equal(t, present, found, "Unexpected index entry for Key: %v, RID: %v", keyValues, targetRid)
}

func checkJoinResult(t *testing.T, joinTree Executor, expected []storage.Tuple) {
	// Build frequency map of expected results
	tupleDesc := storage.NewRawTupleDesc(joinTree.PlanNode().OutputSchema())
	buffer := make([]byte, tupleDesc.BytesPerTuple())

	expectedMap := make(map[string]int)
	for _, tup := range expected {
		tup.WriteToBuffer(buffer, tupleDesc)
		expectedMap[string(buffer)]++
	}

	count := 0
	for joinTree.Next() {
		joinTree.Current().WriteToBuffer(buffer, tupleDesc)
		key := string(buffer)
		remaining, ok := expectedMap[key]
		if !ok || remaining == 0 {
			assert.Fail(t, fmt.Sprintf("Unexpected or extra tuple in join result"))
			return // early stop on first mismatch
		}
		expectedMap[key]--
		count++
	}

	// Verify all expected tuples were found
	missingCount := 0
	for _, remaining := range expectedMap {
		missingCount += remaining
	}
	assert.Equal(t, 0, missingCount, "Some expected tuples were missing from the result")
	assert.Equal(t, len(expected), count, "Total result count mismatch")
}

// simpleNestedLoopJoin calculates the expected join result using an in-memory nested loop.
// It iterates over the provided heaps, merges tuples, and evaluates the predicate.
// This serves as the "Ground Truth" for verification.
func simpleNestedLoopJoin(t *testing.T, leftHeap *TableHeap, rightHeap *TableHeap, predicate planner.Expr) []storage.Tuple {
	var results []storage.Tuple

	leftDesc := leftHeap.StorageSchema()
	rightDesc := rightHeap.StorageSchema()
	joinedTypes := append(leftDesc.GetFieldTypes(), rightDesc.GetFieldTypes()...)
	joinedDesc := storage.NewRawTupleDesc(joinedTypes)

	// Allocate buffers for the iterators
	leftBuf := make([]byte, leftDesc.BytesPerTuple())
	rightBuf := make([]byte, rightDesc.BytesPerTuple())
	outBuf := make([]byte, joinedDesc.BytesPerTuple())

	// Outer Loop (Left Table)
	// We pass nil for transaction to bypass locking for this test verification helper
	leftIter, err := leftHeap.Iterator(nil, transaction.LockModeS, leftBuf)
	require.NoError(t, err)
	defer leftIter.Close()

	for leftIter.Next() {
		leftTuple := storage.FromRawTuple(leftIter.CurrentTuple(), leftDesc, leftIter.CurrentRID())
		rightIter, err := rightHeap.Iterator(nil, transaction.LockModeS, rightBuf)
		require.NoError(t, err)
		for rightIter.Next() {
			rightTuple := storage.FromRawTuple(rightIter.CurrentTuple(), rightDesc, rightIter.CurrentRID())

			// Merge tuples into a temporary buffer
			storage.MergeTuples(outBuf, joinedDesc, leftTuple, rightTuple)
			joinedTuple := storage.FromRawTuple(outBuf, joinedDesc, common.RecordID{})
			// Evaluate the Join Predicate
			// ExprIsTrue returns true only if the result is Non-Null and Non-Zero
			if planner.ExprIsTrue(predicate.Eval(joinedTuple)) {
				results = append(results, joinedTuple.DeepCopy(joinedDesc))
			}
		}
		rightIter.Close()
	}

	return results
}

// checkAggregateResult verifies that the output of the executor matches the expected tuples.
func checkAggregateResult(t *testing.T, aggExec Executor, expected []storage.Tuple) {
	tupleDesc := storage.NewRawTupleDesc(aggExec.PlanNode().OutputSchema())
	buffer := make([]byte, tupleDesc.BytesPerTuple())

	expectedMap := make(map[string]int)
	for _, tup := range expected {
		tup.WriteToBuffer(buffer, tupleDesc)
		expectedMap[string(buffer)]++
	}

	count := 0
	for aggExec.Next() {
		aggExec.Current().WriteToBuffer(buffer, tupleDesc)
		key := string(buffer)
		remaining, ok := expectedMap[key]
		if !ok || remaining == 0 {
			assert.Fail(t, fmt.Sprintf("Unexpected or extra tuple in aggregate result"))
			return
		}
		expectedMap[key]--
		count++
	}

	require.NoError(t, aggExec.Error())

	missingCount := 0
	for _, remaining := range expectedMap {
		missingCount += remaining
	}
	assert.Equal(t, 0, missingCount, "Some expected tuples were missing from the result")
	assert.Equal(t, len(expected), count, "Total result count mismatch")
}
